name: Build n Deploy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install deps
        run: |
          pip install -r requirements.txt

      - name: pyinstaller - onefile
        run: |
          pyinstaller -- onefile \
            --name HappyBlockGame \
            --add-data "assets;assets" \
            --noconsole \
            game.py

      - name: check the dist file
        run: |
          ls -la dist/

      - name: prepare for artifact
        run: |
          mkdir out
          cp dist/HappyBlockGame.exe out/HappyBlockGame-win-x64-${{ github.ref_name }}.exe

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HappyBlockGame-win-x64-${{ github.ref_name }}
          path: dist/HappyBlockGame-win-x64-${{ github.ref_name }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: HappyBlockGame-win-x64-${{ github.ref_name }}
          path: out/

      - name: release artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: out/HappyBlockGame-win-x64-${{ github.ref_name }}.exe
          draft: false
          prerelease: false
